//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNT.Access.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SNT.Access.Activities.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Database File Path.
        /// </summary>
        public static string Access_DB_Path_DisplayName {
            get {
                return ResourceManager.GetString("Access_DB_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input the full path of your AccessDB.
        /// </summary>
        public static string Access_DB_Path_Tooltip {
            get {
                return ResourceManager.GetString("Access_DB_Path_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes and disposes AccessSession.
        /// </summary>
        public static string CloseAccess_Activity_Description {
            get {
                return ResourceManager.GetString("CloseAccess_Activity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Access Session.
        /// </summary>
        public static string CloseAccess_Activity_DisplayName {
            get {
                return ResourceManager.GetString("CloseAccess_Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Table.
        /// </summary>
        public static string DtOut_DisplayName {
            get {
                return ResourceManager.GetString("DtOut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output datatable for your queries.
        /// </summary>
        public static string DtOut_Tooltip {
            get {
                return ResourceManager.GetString("DtOut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes SQL query on Access Session object.
        /// </summary>
        public static string ExecuteAccessQuery_Activity_Description {
            get {
                return ResourceManager.GetString("ExecuteAccessQuery_Activity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Access Query.
        /// </summary>
        public static string ExecuteAccessQuery_Activity_DisplayName {
            get {
                return ResourceManager.GetString("ExecuteAccessQuery_Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns Access Session to be used to query. Remember to dispose when Close session once done.
        /// </summary>
        public static string OpenAccess_Activity_Description {
            get {
                return ResourceManager.GetString("OpenAccess_Activity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Access Session.
        /// </summary>
        public static string OpenAccess_Activity_DisplayName {
            get {
                return ResourceManager.GetString("OpenAccess_Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple activity to query access databases.
        /// </summary>
        public static string QueryAccess_Activity_Description {
            get {
                return ResourceManager.GetString("QueryAccess_Activity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Access Database.
        /// </summary>
        public static string QueryAccess_Activity_DisplayName {
            get {
                return ResourceManager.GetString("QueryAccess_Activity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNT.Access.
        /// </summary>
        public static string QueryDB_Category {
            get {
                return ResourceManager.GetString("QueryDB_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Affected.
        /// </summary>
        public static string RowsAffected_DisplayName {
            get {
                return ResourceManager.GetString("RowsAffected_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows affected by non-query.
        /// </summary>
        public static string RowsAffected_Tooltip {
            get {
                return ResourceManager.GetString("RowsAffected_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access DB Session object.
        /// </summary>
        public static string Session_DisplayName {
            get {
                return ResourceManager.GetString("Session_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access DB Session object.
        /// </summary>
        public static string Session_Tooltip {
            get {
                return ResourceManager.GetString("Session_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Text.
        /// </summary>
        public static string SqlText_DisplayName {
            get {
                return ResourceManager.GetString("SqlText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your SQL text string.
        /// </summary>
        public static string SqlText_Tooltip {
            get {
                return ResourceManager.GetString("SqlText_Tooltip", resourceCulture);
            }
        }
    }
}
